### ISSUE TITLE
do a new release

### ISSUE THREAD

**Issue by vincentfretin** [collective/Products.AutocompleteWidget#6]
I have Products.AutocompleteWidget branch=improved_multivalued_fields_management in a project for years.
The 1.4.0 release on pypi refer to the improved_multivalued_fields_management branch on svn. The project was imported on github since then, but we still have this branch. I fixed the changelog in this branch.
What I propose
rename current master to old_master
and improved_multivalued_fields_management to master
and do a 1.5.0 release for here.

@frisi Can you add me as owner on pypi please https://pypi.python.org/pypi/Products.AutocompleteWidget my login is vincentfretin

**Comment by vincentfretin** [comment]
Apparently this was already the plan back in 2010
https://plone.org/products/autocompletewidget/issues/3

**Comment by frisi** [comment]
just gave you owner rights on pypi @vincentfretin. have a nice day!

**Comment by vincentfretin** [comment]
Thanks! It's done!
